# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('current_date', models.DateField()),
                ('department_name', models.CharField(max_length=264)),
                ('beneficiary_name', models.CharField(max_length=264)),
                ('bill_no', models.IntegerField(default=170, unique=True)),
                ('date_on_doc', models.DateField()),
                ('bill_amount', models.IntegerField(default=10)),
                ('head_code', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField(default=10, unique=True)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='current_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('pro', 'Processed'), ('unp', 'Under Process'), ('def', 'Deficiency in docs')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.current_status'),
        ),
    ]
