# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_auto_20190115_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='Status',
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pro', 'Processed'), ('unp', 'Under Process'), ('def', 'Deficiency in docs')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='current_status',
        ),
    ]
