# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='beneficiary_email',
            field=models.EmailField(default='admin@nitw.ac.in', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[(b'pro', b'Processed'), (b'unp', b'Under Process'), (b'def', b'Deficiency in docs'), (b'rec', b'Received In Accounts')], max_length=20),
        ),
    ]
