# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_auto_20190128_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pro', 'Processed'), ('unp', 'Under Process'), ('def', 'Deficiency in docs'), ('rec', 'Received In Accounts')], max_length=20),
        ),
    ]
